/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jtv.frame.main;

import com.sun.jna.NativeLibrary;
import java.awt.BorderLayout;
import java.awt.Canvas;
import java.awt.Color;
import javax.print.attribute.standard.Media;
import uk.co.caprica.vlcj.binding.LibVlc;
import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;
import uk.co.caprica.vlcj.player.MediaPlayer;
import uk.co.caprica.vlcj.player.MediaPlayerFactory;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;
import uk.co.caprica.vlcj.runtime.RuntimeUtil;

/**
 *
 * @author rolmedo
 */
public class VideoPanel extends javax.swing.JPanel {

    /**
     * Creates new form VideoPanel
     */
    
    public VideoPanel() {
        
        initComponents();
        Canvas c = new Canvas();
        c.setBackground(Color.black);
        c.setVisible(true);

    /* Set the layout */
        this.setLayout(new BorderLayout());

    /* Add the canvas */
      NativeLibrary.addSearchPath("libvlc","/usr/lib/libvlc.so");
      
      
      playerfactory = new MediaPlayerFactory();
      playercomponen = playerfactory.newEmbeddedMediaPlayer();
      playercomponen.setVideoSurface(playerfactory.newVideoSurface(c));
     // this.add(playercomponen);
      this.add(c, BorderLayout.CENTER);
      this.setVisible(true);
      
              

    }
    public void play(String url){
        playercomponen.playMedia("/home/rolmedo/Descargas/SampleVideo_720x480_30mb.mp4");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

         

     public  EmbeddedMediaPlayer playercomponen;
     public MediaPlayerFactory playerfactory;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
